### ISSUE TITLE
notionの導入

### ISSUE THREAD

**Issue by watsonso** [mizuhiki-team/daily_diary_planning#24]
5人まで無料で利用できるのドキュメント管理ツールはnotionを使ってみる

## 🔨 期待する見せ方・挙動 / Expected Behavior
notionが導入されチームメンバーが利用出来ていること

**Comment by nr-ryotaro** [comment]
https://www.notion.so/invite/2c6bbae69bbbfa2d88cdcd3c7e616d300f241ec2
