### ISSUE TITLE
利用するデータベースの決定

### ISSUE THREAD

**Issue by ji-ryoo** [mizuhiki-team/daily_diary_planning#41]
## ⏰ 概要
GoのAPIサーバで利用するデータベース・サービスを決定する

## 💪 実現したいこと・ユーザーストーリー
利用するデータベースを決定し、学習・開発を進められるようにする

## 🉑 受け入れ基準
データベースの決定について、開発者と合意する

## 🔧 タスク
- データベースサービスの調査
- 料金調査

**Comment by ji-ryoo** [comment]
GCPのデータベースサービスでNoSQLに絞ると
- firestore
- Realtime Database
の２択になる[0]

## 先に話しといたほうが良さそうなこと
### firebaseとGCPの違いについて
firebase：Google のモバイル開発プラットフォーム
**クライアントサイド**のエンジニアが使う想定している

GCP；クラウド コンピューティング サービス
**バックエンドやサーバーサイドのデベロッパーに使用される**ことを想定している

firebaseとGCPはCloud Firestore、Cloud Functions、Cloud Storage という 3 つのプロダクトを共有している[1]

## 比較
### firestore
- GCPとFirebase共通のプロダクト。それなのでモバイルとサーバサイドの両方の使用が想定されている。
- GAE/go + firestoreのやってみた系の記事多数
- GCPのコンソールからそのままfirestoreをいじれる
- 無料枠あり。ファーストリリースは無料枠で余裕（https://firebase.google.com/pricing?hl=ja）
- データ構造はコレクション / ドキュメント という概念

### Realtime Database
- firebaseのプロダクト。それなので主にモバイルクライアントから直接利用されることが想定されているはず。
- GAE/go + realtime databaseのやってみた記事なし。Goで操作することはできるみたいだけど。
-  firebaseのコンソールを使う必要あり
- ファーストリリースは無料枠で余裕（https://firebase.google.com/pricing?hl=ja）
- データ構造はほぼjson

### まとめ
GoogleサービスでNoSQLをGAEで使うのであれば、バックエンドの使用が想定されているGCP括りのFirestoreがしっくり来る感じします。
技術的な細かい仕様の違いは[2]と[3]を見てください。
てかもはや今回作るアプリの規模だったらGAEすら使わなくても良い！？
 
### 参考

- [0]Google Cloud データベース
https://cloud.google.com/products/databases/?hl=JA

- [1]Firebase と Google Cloud Platform
https://firebase.google.com/firebase-and-gcp?hl=ja

- [2]データベースを選択: Cloud Firestore または Realtime Database
https://firebase.google.com/docs/database/rtdb-vs-firestore?hl=ja

- [3]Firebase Realtime DatabaseとFirestoreを使い分けていこうなという話
https://techblog.kayac.com/rtdb-vs-firestore

**Comment by ji-ryoo** [comment]
## データモデルのわかりやすいページ
Cloud Firestore データモデル
https://firebase.google.com/docs/firestore/data-model?hl=ja

ここは開発者の意向もあると思うけど、NoSQLのジャンルで
KVSは特に大量データを扱うわけではないし、
インメモリDBはそんなに速度を求めてないし、、
データモデルがjsonっぽいドキュメントDBで良さそう

MongoDB AtlasっていうマネージドなドキュメントDB（無料枠あり）だけど、
GAEから接続するのが若干めんどくさそう（ぐぐるとスタックオーバーフローで接続できない系の投稿あり）
firestoreだったらGCPで一元管理！！！

**Comment by nhsykym** [comment]
Firestoreがよいと思います僕も

**Comment by watsonso** [comment]
GAE + golang + FireStore
